version: '3.1'
services:

  db:
    build:
      context: .
      dockerfile: Dockerfile
    image: "d33pi0/postgres-docker:12.2"
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
