version: '3.1'
services:

  db:
    image: "d33pi0/postgres-docker:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - "postgres_data:/backups"

volumes:
  postgres_data:
